// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void whamess() {
    driver.Navigate().GoToUrl("https://web.whatsapp.com/send?phone=5511981568415&text=sua%20mensagem");
    {
      var element = driver.FindElement(By.CssSelector(".\\_1U1xa > span"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".\\_1U1xa > span"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
  }
}
