// Generated by Selenium IDE
using System;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using NUnit.Framework;
using whamess;

namespace WhaMess

{

    public class Nunit_SendMessage
    {
        private IWebDriver driver;
        private WebDriverWait wait;

        [SetUp]
        public void SetUp()
        {

            //driver = new ChromeDriver();

            string num = TestContext.Parameters.Get("number");

            //string num = "5511981568415";

            //System.Console.WriteLine("numero é "+ num);

            driver = commands.GetBrowserRemote(driver, "chrome", num, "http://192.168.254.128:5555/wd/hub");

            //driver = commands.GetBrowserRemote(driver, "chrome", num, "http://192.168.0.104:5555/wd/hub"); 



            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));



        }

        [TearDown]
        protected void TearDown()
        {
            Thread.Sleep(2000);

            driver.Quit();

        }

        [Test]
        public void SendMessage()
        {

            try
            {

                //driver.Navigate().GoToUrl("https://google.com");

                string message = TestContext.Parameters.Get("text");

                wait.Until(ExpectedConditions.VisibilityOfAllElementsLocatedBy(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")));

                driver.FindElement(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")).Click();

                driver.FindElement(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")).SendKeys(message);

                driver.FindElement(By.CssSelector("#main > footer > div._3ee1T._1LkpH.copyable-area > div._3uMse > div > div._3FRCZ.copyable-text.selectable-text")).SendKeys(Keys.Enter);

                //wait.Until(ExpectedConditions.VisibilityOfAllElementsLocatedBy(By.ClassName("_3Whw5 selectable-text invisible-space copyable-text")));

                Thread.Sleep(2000);


            }

            catch (Exception e)
            {
                Console.WriteLine(e.StackTrace);
            }


        }



    }
}

