// Generated by Selenium IDE
/*
using System;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using NUnit.Framework;
using System.Threading;
using whamess;

namespace Whamess
{
    [TestClass]
    public class whamess
    {
       

        [TestMethod]
        public void sendmessage()
        {


            ChromeOptions options = new ChromeOptions();
            options.AddArgument("--disable-extensions");
            //options.AddArguments("--headless");
            options.AddArguments("--user-data-dir=./User_Data");

            IWebDriver driver = new ChromeDriver(options);

            //driver = commands.GetBrowserLocal(driver, "chrome", "5511981568415");

            string number = "5511981568415";
            string message = "mensagem";


            driver.Navigate().GoToUrl("https://web.whatsapp.com/send?phone=" + number + "&text=" + Uri.EscapeDataString(message));

            driver.Navigate().GoToUrl("https://web.whatsapp.com/send?phone=" + Uri.EscapeDataString(number));

            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(15);

            driver.FindElement(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")).Click();

            driver.FindElement(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")).SendKeys(message);

            driver.FindElement(By.CssSelector("#main > footer > div._3ee1T._1LkpH.copyable-area > div._3uMse > div > div._3FRCZ.copyable-text.selectable-text")).SendKeys(Keys.Enter);

            Thread.Sleep(5000);

            driver.Quit();

        }

    }

}

*/


/* OPEN CHAT WHITOUT RELOAD PAGE JS


const openChat = phone => {
    const link = document.createElement("a");
    link.setAttribute("href", `whatsapp://send?phone=${phone}`);
    document.body.append(link);
    link.click();
    document.body.removeChild(link);
};


openChat('5511981568415')

*/




    // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Threading;
using OpenQA.Selenium;
using whamess;
using Microsoft.VisualStudio.TestTools.UnitTesting;


namespace WhasMess

{
    [TestClass]
    public class WhasMess
    {
        private IWebDriver driver;

        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [TestMethod]
        public void sendmessage()
        {

            //driver = commands.GetBrowserLocal(driver, "chrome", "5511981568415");

            driver = commands.GetBrowserRemote(driver, "chrome", "5511981568415", "http://192.168.99.101:4444/wd/hub");

            //driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();


            try
            {

            string message = "teste";

            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);

            driver.FindElement(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")).Click();

            driver.FindElement(By.CssSelector(".\\_2UL8j > .\\_3FRCZ")).SendKeys(message);

            driver.FindElement(By.CssSelector("#main > footer > div._3ee1T._1LkpH.copyable-area > div._3uMse > div > div._3FRCZ.copyable-text.selectable-text")).SendKeys(Keys.Enter);

                ((ITakesScreenshot)driver).GetScreenshot().SaveAsFile("1.png", ScreenshotImageFormat.Png);

            }

            catch (Exception e)
            {
                Console.WriteLine(e.StackTrace);
            }

            Thread.Sleep(5000);


            driver.Quit();


        }

    }
}

